name: Build and Test


on: 
  push:
    branches:
      - branchMake


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build
        run: make

