name: Build and Test

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++

    - name: Build project
      run: |
        make clean
        make all

